### ISSUE TITLE
bot无响应了

### ISSUE THREAD

**Issue by byicer** [phoenixlzx/telegram-stickerimage-bot#1]
可能是提交图片频率频繁，bot对我无响应了，对其他用户有响应，下面的报错有好多天了。
You currently have a task running, please wait until the task is completed.
忘记说了，就是这个项目的测试环境bot报错，不是自己部署的，谢谢。

**Comment by phoenixlzx** [comment]
估计是有 API 请求卡住了吧。

总之先重启，现在应该没问题了。等下看看加个错误处理...

**Comment by byicer** [comment]
正常了，谢谢。
