### ISSUE TITLE
建议输出图片的格式为png

### ISSUE THREAD

**Issue by Evilmass** [phoenixlzx/telegram-stickerimage-bot#2]
Stickers Bot "/addsticker" 需要的图片格式为png

**Comment by victoriqueko** [comment]
Use `/finish png` instead of `/finish`.

**Comment by Evilmass** [comment]
THX

**Comment by Younes-L** [comment]
@victoriqueko thanks , I don't believe this info is stated anywhere else in the readme or instructions when using the bot, it's very useful
