### ISSUE TITLE
400 undefined

### ISSUE THREAD

**Issue by Drjacky** [phoenixlzx/telegram-stickerimage-bot#21]
<img width="414" alt="Screen Shot 2021-02-27 at 13 11 11" src="https://user-images.githubusercontent.com/2296754/109388162-44b98500-78fd-11eb-9081-e54fe1046ddd.png">

This is the sticker pack: https://t.me/addstickers/RickAndMorty

**Comment by phoenixlzx** [comment]
Animated .TGS is not support currently.
