### ISSUE TITLE
发送动态的 Stickers 出错了

### ISSUE THREAD

**Issue by phh95** [phoenixlzx/telegram-stickerimage-bot#22]
[1/4] Downloading images...
[2/4] Converting images...
Ouch! An error just occurred.
[4/4] Sending the .zip file, may take some time. Check back later!

**Comment by Miuzarte** [comment]
![image](https://user-images.githubusercontent.com/66856838/125157530-21052600-e19e-11eb-9af4-1b3914355e3e.png)
![image](https://user-images.githubusercontent.com/66856838/125157537-295d6100-e19e-11eb-90e0-c317f0903d63.png)
![image](https://user-images.githubusercontent.com/66856838/125157525-19de1800-e19e-11eb-91c3-2bac45ffd586.png)
tg的动态贴纸不是一般的图片

**Comment by phoenixlzx** [comment]
目前不支持动态 sticker。

**Comment by phh95** [comment]
嗯嗯，我后来找到了一个可以导出动态 Sticker 的机器人了：https://github.com/ed-asriyan/tgs-to-gif

**Comment by phoenixlzx** [comment]
现在可以支持 gif 和 tgs 动态 sticker 了。
