### ISSUE TITLE
400 undefined

### ISSUE THREAD

**Issue by Kkerre** [phoenixlzx/telegram-stickerimage-bot#23]
![1DB09FB8-E3F0-4C97-B6DB-D945277A11D8](https://user-images.githubusercontent.com/82369264/114362047-79318980-9ba9-11eb-9971-17e6653a3301.jpeg)

here is the stickers link：https://t.me/addstickers/Peepo_Pepe

**Comment by Hsiao-Feng** [comment]
#21 似乎是不支持动图。

**Comment by phoenixlzx** [comment]
![image](https://github.com/user-attachments/assets/9774d535-66ea-443d-9726-2a9c4950609c)
 It works now.
