### ISSUE TITLE
400 undefined

### ISSUE THREAD

**Issue by pawann-2000** [phoenixlzx/telegram-stickerimage-bot#25]
![image](https://user-images.githubusercontent.com/59572141/126097492-f48ec762-f283-42d3-bd9a-10507380310e.png)
this was an error that came up while I was trying to download stickers from the bot.

Please resolve it so that I can use the bot again. 😃

**Comment by phoenixlzx** [comment]
I tried one and don't see errors here.
Maybe you've sent animated stickers which is not supported.

**Comment by pawann-2000** [comment]
could you please get animated stickers working?

**Comment by phoenixlzx** [comment]
No.

Here is another one that supports GIF
https://github.com/ed-asriyan/tgs-to-gif
