### ISSUE TITLE
bot坏掉了

### ISSUE THREAD

**Issue by ghosthim** [phoenixlzx/telegram-stickerimage-bot#31]
不理我了，可能是坏掉了？🫤

**Comment by phoenixlzx** [comment]
戳了一下貌似是 telegram 的 api 变了，库有点老

不过暂时没时间更新

**Comment by ghosthim** [comment]
🫠好吧

**Comment by z0z0r4** [comment]
考虑最近更新下吗…

**Comment by M3chD09** [comment]
我把目前最新代码拉到服务器上部署了，似乎还可以用  
安装最新的nodejs 16，修改`config.js`后，运行`npm install`和`npm start`就可以了  
这里提供我自己部署的机器人，凑合用 [@stickerset2pack_bot](https://t.me/stickerset2pack_bot)

**Comment by ruhuasiyi** [comment]
> 我把目前最新代码拉到服务器上部署了，似乎还可以用 安装最新的nodejs 16，修改`config.js`后，运行`npm install`和`npm start`就可以了 这里提供我自己部署的机器人，凑合用 [@stickerset2pack_bot](https://t.me/stickerset2pack_bot)
![图片](https://user-images.githubusercontent.com/47032432/210798816-2afd3d04-153a-4c63-b74d-65f95254cf62.png)

**Comment by M3chD09** [comment]
> > 我把目前最新代码拉到服务器上部署了，似乎还可以用 安装最新的nodejs 16，修改`config.js`后，运行`npm install`和`npm start`就可以了 这里提供我自己部署的机器人，凑合用 [@stickerset2pack_bot](https://t.me/stickerset2pack_bot)
> > ![图片](https://user-images.githubusercontent.com/47032432/210798816-2afd3d04-153a-4c63-b74d-65f95254cf62.png)

这个机器人似乎不支持webm和tgs格式的表情包，不知道原作者会不会更新 #34

**Comment by phoenixlzx** [comment]
已经更新到最新版 Telegram API，顺便支持了动态 sticker 导出，以及文件过大时会自动分批发送。有问题的话再开新单子吧
