### ISSUE TITLE
http 400 when downloading some emoji

### ISSUE THREAD

**Issue by Mixlining** [phoenixlzx/telegram-stickerimage-bot#39]
stickpackage:
https://t.me/addstickers/Bocchi_the_Rock_sticker
https://t.me/addstickers/Bocchi_the_Rock_sticker_pack2
download fail;
but https://t.me/addstickers/Spy_Family success

**Comment by ruhuasiyi** [comment]
the same stickpackage, the same issue

**Comment by PerfumeRedwy** [comment]
the same stickpackage, the same issue

**Comment by syouko** [comment]
Error 400 when sticker have GIF.

**Comment by phoenixlzx** [comment]
GIF is now supported.
