### ISSUE TITLE
WebP not converting

### ISSUE THREAD

**Issue by dhalucario** [phoenixlzx/telegram-stickerimage-bot#6]
How to reproduce:
1. Install Fedora 27 (Workstation Edition)
2. Install `dnf install webp-devel`
3. Compile ImageMagick ( ImageMagick 7.0.7-21 Q16 x86_64 2018-01-08 ) ( https://www.imagemagick.org/script/install-source.php )
4. Start bot and create stickers. (Tried with png and jpg)

![i_view64_2018-01-08_20-21-50](https://user-images.githubusercontent.com/10533763/34688209-af2e227a-f4b1-11e7-910f-c5e9744118ad.png)
![i_view64_2018-01-08_20-22-06](https://user-images.githubusercontent.com/10533763/34688212-b074762a-f4b1-11e7-80b2-a89834c52b1b.png)

**Comment by phoenixlzx** [comment]
I have tested with @stickerset2packbot and it works normally.

Do you have further logs or something?

**Comment by mclucario** [comment]
Not at the moment. Im gonna try to get some logs when im home.
